# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f0c5e4bd8b897f5bd942662096fd0d5d06d6d2b68fcbd0ebc8c4572a229fecbdf310b380f4fee939a62aa7c041cb944dd400a2d93601f07f0956601f6d655575

test:
  secret_key_base: eed7a71b528615004a01feecc9d85df124e770a71666f0a9b1700c68460fad561770892b5221eb1cc440887aa7ed8440b76eee83b69062708a99ea19b8a403af

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
